"""
This type stub file was generated by pyright.
"""

from materialyoucolor.hct.hct import Hct

class DislikeAnalyzer:
    @staticmethod
    def is_disliked(hct: Hct) -> bool:
        ...

    @staticmethod
    def fix_if_disliked(hct: Hct) -> Hct:
        ...
