"""
This type stub file was generated by pyright.
"""

class Blend:
    """
    Functions for blending in HCT and CAM16.
    """
    @staticmethod
    def harmonize(design_color: int, source_color: int) -> int:
        """
        Blend the design color's HCT hue towards the key color's HCT
        hue, in a way that leaves the original color recognizable and
        recognizably shifted towards the key color.
        """
        ...

    @staticmethod
    def hct_hue(from_argb: int, to_argb: int, amount: float) -> int:
        """
        Blends hue from one color into another. The chroma and tone of
        the original color are maintained.
        """
        ...

    @staticmethod
    def cam16_ucs(from_argb: int, to_argb: int, amount: float) -> int:
        """
        Blend in CAM16-UCS space.
        """
        ...
