from __future__ import annotations

from flask_htmx_template import web_theme


def test_generate_green() -> None:
    swatch = "#3f6837"
    result = web_theme.generate(swatch)
    fixed: web_theme.FixedColors = {
        "primary_fixed": "#bff0b1",
        "on_primary_fixed": "#002201",
        "primary_fixed_dim": "#a4d397",
        "on_primary_fixed_variant": "#275021",
        "secondary_fixed": "#d7e8cd",
        "on_secondary_fixed": "#121f0f",
        "secondary_fixed_dim": "#bbccb2",
        "on_secondary_fixed_variant": "#3c4b37",
        "tertiary_fixed": "#bcebef",
        "on_tertiary_fixed": "#002022",
        "tertiary_fixed_dim": "#a0cfd2",
        "on_tertiary_fixed_variant": "#1e4d51",
        "white": "#fff",
        "black": "#000",
    }
    light: web_theme.Colors = {
        "primary": "#3f6837",
        "on_primary": "#ffffff",
        "primary_container": "#bff0b1",
        "on_primary_container": "#275021",
        "inverse_primary": "#a4d397",
        "secondary": "#53634e",
        "on_secondary": "#ffffff",
        "secondary_container": "#d7e8cd",
        "on_secondary_container": "#3c4b37",
        "tertiary": "#386569",
        "on_tertiary": "#ffffff",
        "tertiary_container": "#bcebef",
        "on_tertiary_container": "#1e4d51",
        "error": "#ba1a1a",
        "on_error": "#ffffff",
        "error_container": "#ffdad6",
        "on_error_container": "#93000a",
        "surface": "#f8fbf1",
        "on_surface": "#191d17",
        "surface_dim": "#d8dbd2",
        "surface_bright": "#f8fbf1",
        "surface_variant": "#dfe4d8",
        "on_surface_variant": "#42493f",
        "inverse_surface": "#2e322b",
        "inverse_on_surface": "#eff2e8",
        "surface_container_lowest": "#ffffff",
        "surface_container_low": "#f2f5eb",
        "surface_container": "#ecefe5",
        "surface_container_high": "#e6e9e0",
        "surface_container_highest": "#e1e4da",
        "outline": "#73796e",
        "outline_variant": "#c2c8bc",
        "shadow": "#000000",
        "scrim": "#000000",
    }
    dark: web_theme.Colors = {
        "primary": "#a4d397",
        "on_primary": "#10380c",
        "primary_container": "#275021",
        "on_primary_container": "#bff0b1",
        "inverse_primary": "#3f6837",
        "secondary": "#bbccb2",
        "on_secondary": "#263422",
        "secondary_container": "#3c4b37",
        "on_secondary_container": "#d7e8cd",
        "tertiary": "#a0cfd2",
        "on_tertiary": "#00373a",
        "tertiary_container": "#1e4d51",
        "on_tertiary_container": "#bcebef",
        "error": "#ffb4ab",
        "on_error": "#690005",
        "error_container": "#93000a",
        "on_error_container": "#ffdad6",
        "surface": "#11140f",
        "on_surface": "#e1e4da",
        "surface_dim": "#11140f",
        "surface_bright": "#363a34",
        "surface_variant": "#42493f",
        "on_surface_variant": "#c2c8bc",
        "inverse_surface": "#e1e4da",
        "inverse_on_surface": "#2e322b",
        "surface_container_lowest": "#0b0f0a",
        "surface_container_low": "#191d17",
        "surface_container": "#1d211b",
        "surface_container_high": "#272b25",
        "surface_container_highest": "#32362f",
        "outline": "#8d9387",
        "outline_variant": "#42493f",
        "shadow": "#000000",
        "scrim": "#000000",
    }
    target: web_theme.Theme = {
        "fixed": fixed,
        "light": light,
        "dark": dark,
    }
    assert target == result
