"""
This type stub file was generated by pyright.
"""

from .scheme import Scheme as Scheme
from .scheme_android import SchemeAndroid as SchemeAndroid
from .scheme_content import SchemeContent as SchemeContent
from .scheme_expressive import SchemeExpressive as SchemeExpressive
from .scheme_fidelity import SchemeFidelity as SchemeFidelity
from .scheme_fruit_salad import SchemeFruitSalad as SchemeFruitSalad
from .scheme_monochrome import SchemeMonochrome as SchemeMonochrome
from .scheme_neutral import SchemeNeutral as SchemeNeutral
from .scheme_rainbow import SchemeRainbow as SchemeRainbow
from .scheme_tonal_spot import SchemeTonalSpot as SchemeTonalSpot
from .scheme_vibrant import SchemeVibrant as SchemeVibrant
