"""
This type stub file was generated by pyright.
"""

from materialyoucolor.dynamiccolor.dynamic_scheme import (
    DynamicScheme,
    Platform,
    SpecVersion,
)
from materialyoucolor.hct.hct import Hct

class SchemeFruitSalad(DynamicScheme):
    def __init__(self, source_color_hct: Hct, is_dark: bool, contrast_level: float, spec_version: SpecVersion = ..., platform: Platform = ...) -> None:
        ...
