"""
This type stub file was generated by pyright.
"""

from typing import Any

from materialyoucolor.palettes.core_palette import CorePalette

class SchemeAndroid:
    def __init__(self, props: dict[str, Any]) -> None:
        ...

    @staticmethod
    def light_from_rgb(rgb: list[int]) -> SchemeAndroid:
        ...

    @staticmethod
    def light(argb: int) -> SchemeAndroid:
        ...

    @staticmethod
    def light_content(argb: int) -> SchemeAndroid:
        ...

    @staticmethod
    def light_from_core_palette(core: CorePalette) -> SchemeAndroid:
        ...

    @staticmethod
    def dark_from_rgb(rgb: list[int]) -> SchemeAndroid:
        ...

    @staticmethod
    def dark(argb: int) -> SchemeAndroid:
        ...

    @staticmethod
    def dark_content(argb: int) -> SchemeAndroid:
        ...

    @staticmethod
    def dark_from_core_palette(core: CorePalette) -> SchemeAndroid:
        ...

    def to_json(self) -> dict[str, Any]:
        ...
