"""
This type stub file was generated by pyright.
"""

from typing import Optional

class CorePaletteColors:
    def __init__(
        self,
        primary: int,
        secondary: Optional[int] = ...,
        tertiary: Optional[int] = ...,
        neutral: Optional[int] = ...,
        neutral_variant: Optional[int] = ...,
        error: Optional[int] = ...,
    ) -> None: ...

class CorePalette:
    def __init__(self, argb: int, is_content: bool) -> None: ...
    @staticmethod
    def of(argb: int) -> CorePalette: ...
    @staticmethod
    def content_of(argb: int) -> CorePalette: ...
    @staticmethod
    def from_colors(colors: CorePaletteColors) -> CorePalette: ...
    @staticmethod
    def content_from_colors(colors: CorePaletteColors) -> CorePalette: ...
