"""
This type stub file was generated by pyright.
"""

from materialyoucolor.hct.hct import Hct

class KeyColor:
    def __init__(self, hue: float, requested_chroma: float) -> None:
        ...

    def create(self) -> Hct:
        ...

    def max_chroma(self, tone: int) -> float:
        ...



class TonalPalette:
    def __init__(self, hue: float, chroma: float, key_color: Hct) -> None:
        ...

    @staticmethod
    def from_int(argb: int) -> TonalPalette:
        ...

    @staticmethod
    def from_hct(hct: Hct) -> TonalPalette:
        ...

    @staticmethod
    def from_hue_and_chroma(hue: float, chroma: float) -> TonalPalette:
        ...

    def tone(self, tone: float) -> int:
        ...

    def get_hct(self, tone: float) -> Hct:
        ...

    def average_argb(self, argb1: int, argb2: int) -> int:
        ...
