"""
This type stub file was generated by pyright.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Literal, TYPE_CHECKING

from materialyoucolor.hct.hct import Hct

if TYPE_CHECKING:
    from materialyoucolor.dynamiccolor.dynamic_color import DynamicColor
    from materialyoucolor.dynamiccolor.dynamic_scheme import DynamicScheme

SpecVersion = Literal["2021", "2025"]
COLOR_NAMES = ...
class ColorSpecDelegate(ABC):
    """
    A delegate that provides the dynamic color constraints for
    MaterialDynamicColors.

    This is used to allow for different color constraints for different spec
    versions.
    """
    @abstractmethod
    def highestSurface(self, s: DynamicScheme) -> DynamicColor:
        ...



_spec_2021 = ...
_spec_2025 = ...
def get_spec(spec_version: SpecVersion) -> ColorSpecDelegate:
    ...

class ColorCalculationDelegate:
    def get_hct(self, scheme: DynamicScheme, color: DynamicColor) -> Hct:
        ...

    def get_tone(self, scheme: DynamicScheme, color: DynamicColor) -> float:
        ...



class ColorCalculationDelegateImpl2021(ColorCalculationDelegate):
    def get_hct(self, scheme: DynamicScheme, color: DynamicColor) -> Hct:
        ...

    def get_tone(self, scheme: DynamicScheme, color: DynamicColor) -> float:
        ...



class ColorCalculationDelegateImpl2025(ColorCalculationDelegate):
    def get_hct(self, scheme: DynamicScheme, color: DynamicColor) -> Hct:
        ...

    def get_tone(self, scheme: DynamicScheme, color: DynamicColor) -> float:
        ...



_spec2021_calc = ...
_spec2025_calc = ...
def get_color_calculation_delegate(spec_version: SpecVersion) -> ColorCalculationDelegate:
    ...
