"""
This type stub file was generated by pyright.
"""

class ContrastCurve:
    def __init__(
        self, low: float, normal: float, medium: float, high: float
    ) -> None: ...
    def get(self, contrast_level: float) -> float: ...
