"""
This type stub file was generated by pyright.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Optional, TYPE_CHECKING

from materialyoucolor.dynamiccolor.color_spec import SpecVersion
from materialyoucolor.dynamiccolor.contrast_curve import ContrastCurve
from materialyoucolor.dynamiccolor.tone_delta_pair import ToneDeltaPair
from materialyoucolor.hct.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

if TYPE_CHECKING:
    from materialyoucolor.dynamiccolor.dynamic_scheme import DynamicScheme

@dataclass
class FromPaletteOptions:
    name: str = ...
    palette: Callable[[DynamicScheme], TonalPalette] = ...
    tone: Callable[[DynamicScheme], float] = ...
    chroma_multiplier: Optional[Callable[[DynamicScheme], float]] = ...
    is_background: bool = ...
    background: Optional[Callable[[DynamicScheme], DynamicColor]] = ...
    second_background: Optional[Callable[[DynamicScheme], DynamicColor]] = ...
    contrast_curve: Optional[Callable[[DynamicScheme], ContrastCurve]] = ...
    tone_delta_pair: Optional[Callable[[DynamicScheme], ToneDeltaPair]] = ...


def validate_extended_color(original_color: DynamicColor, spec_version: SpecVersion, extended_color: DynamicColor) -> None:
    ...

def extend_spec_version(original: DynamicColor, spec: SpecVersion, extended: DynamicColor) -> DynamicColor:
    ...

class DynamicColor(FromPaletteOptions):
    hct_cache: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @classmethod
    def from_palette(cls, *args: Any, **kwargs: Any) -> DynamicColor:
        ...

    @staticmethod
    def get_initial_tone_from_background(background: Optional[Callable[[DynamicScheme], DynamicColor]] = ...) -> Callable[[DynamicScheme], float]:
        ...

    def clone(self) -> DynamicColor:
        ...

    def clear_cache(self) -> None:
        ...

    def get_argb(self, scheme: DynamicScheme) -> int:
        ...

    def get_hex(self, scheme: DynamicScheme) -> str:
        ...

    def get_rgba(self, scheme: DynamicScheme) -> list[int]:
        ...

    def get_hct(self, scheme: DynamicScheme) -> Hct:
        ...

    def get_tone(self, scheme: DynamicScheme) -> float:
        ...

    @staticmethod
    def foreground_tone(bg_tone: float, ratio: float) -> float:
        ...

    @staticmethod
    def tone_prefers_light_foreground(tone: float) -> bool:
        ...

    @staticmethod
    def tone_allows_light_foreground(tone: float) -> bool:
        ...

    @staticmethod
    def enable_light_foreground(tone: float) -> float:
        ...
