"""
This type stub file was generated by pyright.
"""

from typing import Literal

from materialyoucolor.dynamiccolor.dynamic_color import DynamicColor
from materialyoucolor.dynamiccolor.variant import Variant
from materialyoucolor.hct.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

SpecVersion = Literal["2021", "2025"]
Platform = Literal["phone", "watch"]

class DynamicSchemePalettesDelegate:
    def get_primary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_secondary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_tertiary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_variant_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_error_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette | None: ...

class DynamicScheme:
    DEFAULT_SPEC_VERSION: SpecVersion = ...
    DEFAULT_PLATFORM: Platform = ...
    def __init__(
        self,
        source_color_hct: Hct,
        variant: Variant,
        contrast_level: float,
        is_dark: bool,
        platform: Platform = ...,
        spec_version: SpecVersion = ...,
        primary_palette: TonalPalette = ...,
        secondary_palette: TonalPalette = ...,
        tertiary_palette: TonalPalette = ...,
        neutral_palette: TonalPalette = ...,
        neutral_variant_palette: TonalPalette = ...,
        error_palette: TonalPalette = ...,
    ) -> None: ...
    def __str__(self) -> str: ...
    @staticmethod
    def get_piecewise_hue(
        source_color_hct: Hct, hue_breakpoints: list[float], hues: list[float]
    ) -> float: ...
    @staticmethod
    def get_rotated_hue(
        source_color_hct: Hct, hue_breakpoints: list[float], rotations: list[float]
    ) -> float: ...
    def get_argb(self, dynamic_color: DynamicColor) -> int: ...
    def get_hct(self, dynamic_color: DynamicColor) -> Hct: ...

class DynamicSchemePalettesDelegateImpl2021(DynamicSchemePalettesDelegate):
    def get_primary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_secondary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_tertiary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_variant_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_error_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette | None: ...

class DynamicSchemePalettesDelegateImpl2025(DynamicSchemePalettesDelegate):
    def get_primary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_secondary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_tertiary_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_neutral_variant_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette: ...
    def get_error_palette(
        self,
        variant: Variant,
        source_color_hct: Hct,
        is_dark: bool,
        platform: Platform,
        contrast_level: float,
    ) -> TonalPalette | None: ...

_spec2021 = ...
_spec2025 = ...

def get_spec(spec_version: SpecVersion) -> DynamicSchemePalettesDelegate: ...
