"""
This type stub file was generated by pyright.
"""

from __future__ import annotations

from typing import Literal, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from materialyoucolor.dynamiccolor.dynamic_color import DynamicColor

TonePolarity = Literal[
    "darker", "lighter", "nearer", "farther", "relative_darker", "relative_lighter"
]
DeltaConstraint = Literal["exact", "nearer", "farther"]

class ToneDeltaPair:
    def __init__(
        self,
        role_a: DynamicColor,
        role_b: DynamicColor,
        delta: float,
        polarity: TonePolarity,
        stay_together: bool,
        constraint: Optional[DeltaConstraint] = ...,
    ) -> None: ...
