"""
This type stub file was generated by pyright.
"""

from materialyoucolor.hct.viewing_conditions import ViewingConditions

class Cam16:
    def __init__(self, hue: float, chroma: float, j: float, q: float, m: float, s: float, jstar: float, astar: float, bstar: float) -> None:
        ...

    def distance(self, other: Cam16) -> float:
        ...

    @staticmethod
    def from_int(argb: int) -> Cam16:
        ...

    @staticmethod
    def from_int_in_viewing_conditions(argb: int, viewing_conditions: ViewingConditions) -> Cam16:
        ...

    @staticmethod
    def from_xyz_in_viewing_conditions(x: float, y: float, z: float, viewing_conditions: ViewingConditions) -> Cam16:
        ...

    @staticmethod
    def from_jch(j: float, c: float, h: float) -> Cam16:
        ...

    @staticmethod
    def from_jch_in_viewing_conditions(j: float, c: float, h: float, viewing_conditions: ViewingConditions) -> Cam16:
        ...

    @staticmethod
    def from_ucs(jstar: float, astar: float, bstar: float) -> Cam16:
        ...

    @staticmethod
    def from_ucs_in_viewing_conditions(jstar: float, astar: float, bstar: float, viewing_conditions: ViewingConditions) -> Cam16:
        ...

    def to_int(self) -> int:
        ...

    def viewed(self, viewing_conditions: ViewingConditions) -> int:
        ...

    def xyz_in_viewing_conditions(self, viewing_conditions: ViewingConditions) -> list[float]:
        ...
