"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from materialyoucolor.hct.viewing_conditions import ViewingConditions

if TYPE_CHECKING:
    ...
class Hct:
    def __init__(self, argb: int) -> None:
        ...

    def set_internal_state(self, argb: int) -> None:
        ...

    @staticmethod
    def from_hct(hue: float, chroma: float, tone: float) -> Hct:
        ...

    @staticmethod
    def from_int(argb: int) -> Hct:
        ...

    def to_int(self) -> int:
        ...

    def to_rgba(self) -> list[int]:
        ...

    @property
    def hue(self) -> float:
        ...

    @hue.setter
    def hue(self, new_hue: float) -> None:
        ...

    @property
    def chroma(self) -> float:
        ...

    @chroma.setter
    def chroma(self, new_chroma: float) -> None:
        ...

    @property
    def tone(self) -> float:
        ...

    @tone.setter
    def tone(self, new_tone: float) -> None:
        ...

    def set_value(self, property_name: str, value: float) -> None:
        ...

    def __str__(self) -> str:
        ...

    @staticmethod
    def is_blue(hue: float) -> bool:
        ...

    @staticmethod
    def is_yellow(hue: float) -> bool:
        ...

    @staticmethod
    def is_cyan(hue: float) -> bool:
        ...

    def in_viewing_conditions(self, vc: ViewingConditions) -> Hct:
        ...
