"""
This type stub file was generated by pyright.
"""

class ViewingConditions:
    def __init__(self, n: float, aw: float, nbb: float, ncb: float, c: float, nc: float, rgb_d: list[float], fl: float, f_l_root: float, z: float) -> None:
        ...

    @staticmethod
    def make(white_point: list[float] = ..., adapting_luminance: float = ..., background_lstar: float = ..., surround: float = ..., discounting_illuminant: bool = ...) -> ViewingConditions:
        ...
